import 'package:upds_info/models/carrera.dart';

final carreras = <Carrera>[
  Carrera(
    id: 1,
    nombre: 'Ingeniería Civil',
    sigla: 'IC',
    matricula: '123456',
    image1: 'https://example.com/ingenieria_civil.jpg',
  ),
  Carrera(
    id: 2,
    nombre: 'Ingenieria de Sistemas',
    sigla: 'IDS',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  Carrera(
    id: 3,
    nombre: 'Ingenieria en Redes y Telecomunicaciones',
    sigla: 'IRT',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  Carrera(
    id: 4,
    nombre: 'Administración de Empresas',
    sigla: 'ADE',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  Carrera(
    id: 5,
    nombre: 'Psicopedagogia',
    sigla: 'PSI',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  
  Carrera(
    id: 6,
    nombre: 'Ingenieria Comercial',
    sigla: 'IC',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  Carrera(
    id: 7,
    nombre: 'Relaciones Internacionales',
    sigla: 'RI',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  Carrera(
    id: 2,
    nombre: 'Contaduria Publica',
    sigla: 'CP',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
  Carrera(
    id: 2,
    nombre: 'Derecho',
    sigla: 'DER',
    matricula: '789012',
    image1: 'https://example.com/psicologia.jpg',
    image2: 'https://example.com/psicologia2.jpg',
  ),
];